name: Deploy docs

on:
  push:
    branches: [ stable ]
    paths:
    - '**.ts'
    - '**.json'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Build docs
      run: npm run docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./public
